services:
    cabot.translation.listener:
        class: cabot\translation\event\listener
        arguments:
            - '@language'
            - '@template'
        tags:
            - { name: event.listener }
